const defaults=[['麻辣烫','🥘'],['黄焖鸡','🍗'],['兰州拉面','🍜'],['寿司','🍣'],['牛肉饭','🍛'],['轻食沙拉','🥗'],['重庆小面','🍜'],['汉堡薯条','🍔'],['饺子','🥟'],['猪脚饭','🍚'],['砂锅米线','🍲'],['披萨','🍕']];
let menu=defaults.map(x=>[...x]),rotation=0,busy=false;
const $=id=>document.getElementById(id),colors=['#c8ee59','#f9f8ed','#ffbfd6','#e7eccf'];
function render(){const n=menu.length,step=360/n;let parts='';menu.forEach(([name],i)=>{const start=(i*step-90-step/2)*Math.PI/180,end=start+step*Math.PI/180;const x1=250+250*Math.cos(start),y1=250+250*Math.sin(start),x2=250+250*Math.cos(end),y2=250+250*Math.sin(end);parts+=`<path d="M250 250 L${x1} ${y1} A250 250 0 ${step>180?1:0} 1 ${x2} ${y2} Z" fill="${colors[i%colors.length]}" stroke="#22251e" stroke-width="1.5"/>`;});$('wheel-svg').innerHTML=parts;menu.forEach(([name],i)=>{const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.setAttribute('transform',`rotate(${i*step} 250 250)`);const t=document.createElementNS(g.namespaceURI,'text');t.setAttribute('x','250');t.setAttribute('y','77');t.setAttribute('text-anchor','middle');t.setAttribute('fill','#22251e');t.setAttribute('font-size',n>13?'16':'18');t.setAttribute('font-weight','750');t.textContent=name;if(name.length>4){t.setAttribute('textLength',String(Math.min(100,2*173*Math.sin(Math.PI/n)-12)));t.setAttribute('lengthAdjust','spacingAndGlyphs');}g.append(t);$('wheel-svg').append(g)});$('options').replaceChildren();menu.forEach(([name,emoji],i)=>{const chip=document.createElement('span');chip.className='food-chip';const text=document.createElement('span');text.textContent=name;const b=document.createElement('button');b.textContent='×';b.setAttribute('aria-label',`移除${name}`);b.disabled=busy;b.onclick=()=>{if(busy)return;if(menu.length<=2){$('menu-message').textContent='再留两道吧，转盘才有得选。';return}menu.splice(i,1);resetWheel();render();};chip.append(text,b);$('options').append(chip)});$('count').textContent=n;}
function resetWheel(){rotation=0;$('wheel').style.transition='none';$('wheel').style.transform='rotate(0deg)';void $('wheel').offsetWidth;$('wheel').style.transition='';$('menu-message').textContent='至少保留 2 项，最多 16 项。';$('result-emoji').textContent='🍽️';$('result-kicker').textContent='今天的午餐是……';$('result-title').textContent='等一个好吃的答案';$('result-description').textContent='轻轻转一下，结束漫长的纠结。';}
function randomIndex(n){const a=new Uint32Array(1),limit=Math.floor(4294967296/n)*n;do{crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%n;}
function setBusy(value){busy=value;for(const el of document.querySelectorAll('button,input'))el.disabled=value;$('spin').firstChild.textContent=value?'正在挑选美味… ':'再转一次 ';$('center-spin').setAttribute('aria-label',value?'转盘旋转中':'开始转盘');}
function celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<36;i++){const el=document.createElement('i');el.className='confetti';el.style.left=Math.random()*100+'vw';el.style.background=colors[i%4];el.style.setProperty('--drift',(Math.random()-.5)*250+'px');el.style.animationDelay=Math.random()*.3+'s';document.body.append(el);setTimeout(()=>el.remove(),3000)}}
async function spin(){if(busy)throw new Error('转盘正在旋转，请稍候。');const i=randomIndex(menu.length),step=360/menu.length,target=(360-i*step)%360,current=rotation%360;rotation+=1800+(target-current+360)%360;setBusy(true);$('result-emoji').textContent='✨';$('result-kicker').textContent='美味正在路上';$('result-title').textContent='让缘分转一会儿';$('result-description').textContent='今天的选择，就快揭晓。';$('spin-note').textContent='指针停在哪里，今天就吃哪一道。';$('wheel').style.transform=`rotate(${rotation}deg)`;await new Promise(resolve=>setTimeout(resolve,matchMedia('(prefers-reduced-motion: reduce)').matches?80:4550));const [name,emoji]=menu[i];$('result-emoji').textContent=emoji;$('result-kicker').textContent='就决定是你了！';$('result-title').textContent=name;$('result-description').textContent='别纠结啦，带着好心情去吃饭吧。';$('spin-note').textContent='还想换个口味？再转一次也没关系。';setBusy(false);celebrate();return {lunch:name};}
$('spin').onclick=()=>spin();$('center-spin').onclick=()=>spin();$('reset').onclick=()=>{if(busy)return;menu=defaults.map(x=>[...x]);resetWheel();render()};$('add-form').onsubmit=e=>{e.preventDefault();if(busy)return;const name=$('food-input').value.trim();if(!name){$('menu-message').textContent='先写一道你想吃的吧。';return}if(menu.length>=16){$('menu-message').textContent='菜单已满 16 项，先移除一道吧。';return}if(menu.some(x=>x[0]===name)){$('menu-message').textContent='这道美味已经在菜单里啦。';return}menu.push([name,'🍽️']);$('food-input').value='';resetWheel();render();$('food-input').focus();};render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'spin_lunch_wheel',title:'随机选择午餐',description:'旋转当前午餐转盘，等待结果揭晓并返回选中的午餐。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('此操作不接受参数。');return spin();}})).catch(()=>{})}catch{}}
